version: "3"
services:
  order_service:
    build: ./order-service
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      MARIA_HOST: order_mgmt_db
      MARIA_USERNAME: user1
      MARIA_PASSWORD: P@ssw0rd
      MARIA_DATABASE: order_management
      MARIA_PORT: 3306
      REDIS_CONNECTION_STRING: redis://default:P@ssw0rd@redis:6379
    links:
      - order_mgmt_db
      - redis
  payment_service:
    build: ./payment-service
    ports:
      - 3002:3002
    environment:
      PORT: 3002
      MARIA_HOST: payment_mgmt_db
      MARIA_USERNAME: user1
      MARIA_PASSWORD: P@ssw0rd
      MARIA_DATABASE: payment_management
      MARIA_PORT: 3306
      REDIS_CONNECTION_STRING: redis://default:P@ssw0rd@redis:6379
    links:
      - payment_mgmt_db
      - redis
  order_mgmt_db:
    image: mariadb:10.4
    ports:
      - 3311:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_PASSWORD=P@ssw0rd
      - MYSQL_USER=user1
      - MYSQL_DATABASE=order_management
    volumes:
      - ${PWD}/local/mariadb:/var/lib/mariadb/data
  payment_mgmt_db:
    image: mariadb:10.4
    ports:
      - 3312:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_PASSWORD=P@ssw0rd
      - MYSQL_USER=user1
      - MYSQL_DATABASE=payment_management
    volumes:
      - ${PWD}/local/mariadb:/var/lib/mariadb/data
  redis:
    build:
      context: .
      dockerfile: ./docker/redis.Dockerfile
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: P@ssw0rd
